#!/bin/bash
set -euo pipefail

WORKDIR="${HOME}/web-framework-handson-02"

echo "========================================"
echo " CGIハンズオン環境セットアップ"
echo " 第2回：CGIという原点"
echo "========================================"

# --------------------------------------------------
# 作業ディレクトリの作成
# --------------------------------------------------
echo ""
echo "[1/6] 作業ディレクトリを作成..."
mkdir -p "${WORKDIR}"
cd "${WORKDIR}"

# --------------------------------------------------
# Dockerfileの作成
# --------------------------------------------------
echo "[2/6] Dockerfileを作成..."
cat > Dockerfile << 'DOCKERFILE'
FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      apache2 \
      perl \
      curl \
    && rm -rf /var/lib/apt/lists/*

# CGIモジュールを有効化
RUN a2enmod cgi

# CGIスクリプトのコピー
COPY cgi-bin/ /usr/lib/cgi-bin/
RUN chmod 755 /usr/lib/cgi-bin/*.pl

# HTMLファイルのコピー
COPY html/ /var/www/html/

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
DOCKERFILE

# --------------------------------------------------
# 演習1: Hello, World! CGIスクリプト
# --------------------------------------------------
echo "[3/6] 演習1: Hello, World! CGIスクリプトを作成..."
mkdir -p cgi-bin

cat > cgi-bin/hello.pl << 'SCRIPT'
#!/usr/bin/perl
print "Content-type: text/html\n\n";
print "<html><body>\n";
print "<h1>Hello from CGI!</h1>\n";
print "<p>This page was generated by a Perl CGI script.</p>\n";
print "<p>Server time: " . localtime() . "</p>\n";
print "</body></html>\n";
SCRIPT

# --------------------------------------------------
# 演習2: 環境変数の可視化
# --------------------------------------------------
echo "[4/6] 演習2: 環境変数可視化スクリプトを作成..."

cat > cgi-bin/env.pl << 'SCRIPT'
#!/usr/bin/perl
print "Content-type: text/html\n\n";
print "<html><body>\n";
print "<h1>CGI Environment Variables</h1>\n";
print "<table border='1' cellpadding='5'>\n";
print "<tr><th>Variable</th><th>Value</th></tr>\n";

my @cgi_vars = qw(
    REQUEST_METHOD QUERY_STRING CONTENT_LENGTH CONTENT_TYPE
    PATH_INFO SCRIPT_NAME SERVER_NAME SERVER_PORT SERVER_PROTOCOL
    REMOTE_ADDR REMOTE_HOST GATEWAY_INTERFACE
    HTTP_USER_AGENT HTTP_ACCEPT HTTP_HOST HTTP_COOKIE
);

for my $var (@cgi_vars) {
    my $val = $ENV{$var} // "(not set)";
    print "<tr><td>$var</td><td>$val</td></tr>\n";
}

print "</table>\n";
print "</body></html>\n";
SCRIPT

# --------------------------------------------------
# 演習3: フォーム処理（GET/POST）
# --------------------------------------------------
echo "[5/6] 演習3: フォーム処理スクリプトを作成..."

cat > cgi-bin/form.pl << 'SCRIPT'
#!/usr/bin/perl
use strict;
use warnings;

my %params;
my $method = $ENV{'REQUEST_METHOD'};

if ($method eq 'GET') {
    my $query = $ENV{'QUERY_STRING'} || '';
    for my $pair (split(/&/, $query)) {
        my ($key, $value) = split(/=/, $pair, 2);
        $value //= '';
        $value =~ s/\+/ /g;
        $value =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/eg;
        $params{$key} = $value;
    }
} elsif ($method eq 'POST') {
    my $length = $ENV{'CONTENT_LENGTH'} || 0;
    my $body = '';
    read(STDIN, $body, $length);
    for my $pair (split(/&/, $body)) {
        my ($key, $value) = split(/=/, $pair, 2);
        $value //= '';
        $value =~ s/\+/ /g;
        $value =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/eg;
        $params{$key} = $value;
    }
}

print "Content-type: text/html\n\n";
print "<html><body>\n";
print "<h1>Form Result</h1>\n";
print "<p>Method: $method</p>\n";
print "<p>Name: $params{'name'}</p>\n" if $params{'name'};
print "<p>Message: $params{'message'}</p>\n" if $params{'message'};
print "<hr>\n";
print "<a href='/form.html'>Back to form</a>\n";
print "</body></html>\n";
SCRIPT

mkdir -p html

cat > html/form.html << 'HTML'
<html>
<head><title>CGI Form Example</title></head>
<body>
<h1>CGI Form Example</h1>

<h2>GET Method</h2>
<form action="/cgi-bin/form.pl" method="GET">
  <label>Name: <input type="text" name="name"></label><br>
  <label>Message: <input type="text" name="message"></label><br>
  <input type="submit" value="Send (GET)">
</form>

<h2>POST Method</h2>
<form action="/cgi-bin/form.pl" method="POST">
  <label>Name: <input type="text" name="name"></label><br>
  <label>Message: <input type="text" name="message"></label><br>
  <input type="submit" value="Send (POST)">
</form>
</body>
</html>
HTML

# --------------------------------------------------
# 演習4: アクセスカウンター
# --------------------------------------------------
echo "[6/6] 演習4: アクセスカウンタースクリプトを作成..."

cat > cgi-bin/counter.pl << 'SCRIPT'
#!/usr/bin/perl
use strict;
use warnings;
use Fcntl qw(:flock);

my $count_file = '/tmp/cgi_counter.dat';

open(my $fh, '+>>', $count_file) or die "Cannot open: $!";
flock($fh, LOCK_EX) or die "Cannot lock: $!";

seek($fh, 0, 0);
my $count = <$fh> || 0;
chomp $count;
$count++;

seek($fh, 0, 0);
truncate($fh, 0);
print $fh "$count\n";
close($fh);

print "Content-type: text/html\n\n";
print "<html><body>\n";
print "<h1>Access Counter</h1>\n";
print "<p>You are visitor number: <strong>$count</strong></p>\n";
print "<p>Process ID: $$</p>\n";
print "<p>Each request runs in a new process.</p>\n";
print "<p>The counter persists because it is stored in a file,</p>\n";
print "<p>not in memory (which is destroyed when the process ends).</p>\n";
print "</body></html>\n";
SCRIPT

# --------------------------------------------------
# Docker イメージのビルドと起動
# --------------------------------------------------
echo ""
echo "========================================"
echo " セットアップ完了"
echo "========================================"
echo ""
echo "以下のコマンドでDockerコンテナを起動してください:"
echo ""
echo "  cd ${WORKDIR}"
echo "  docker build -t cgi-lab ."
echo "  docker run -it --rm -p 8080:80 --name cgi-lab cgi-lab"
echo ""
echo "アクセス方法:"
echo "  curl http://localhost:8080/cgi-bin/hello.pl"
echo "  curl http://localhost:8080/cgi-bin/env.pl"
echo "  curl 'http://localhost:8080/cgi-bin/env.pl?name=Yusuke'"
echo "  curl http://localhost:8080/cgi-bin/form.pl?name=Test&message=Hello"
echo "  curl -X POST http://localhost:8080/cgi-bin/form.pl -d 'name=Test&message=Hello'"
echo "  curl http://localhost:8080/cgi-bin/counter.pl"
echo ""
echo "ブラウザでフォームを試す:"
echo "  http://localhost:8080/form.html"
echo ""
